### ISSUE TITLE
Error message on latest version (1.1.0)

### ISSUE THREAD

**Issue by enoversum** [adielBm/Flow.Launcher.Plugin.Weather#2]
Hello there,
happily tried out your plugin, which worked fine the first time I tried it. But after updating to 1.1.0, an error message appears on every search.

Since it only shows on the interface, here is a screenshot of the message:

![image](https://github.com/user-attachments/assets/09aca78c-caa4-4291-808c-46c45d381312)

 Also, I cannot see your mentioned default city option anywhere in settings.

**Comment by adielBm** [comment]
thank you for letting me know!

I couldn't find the reason for this error. It works fine for me.

you're saying that there are no logs, so if you'd like to help me fix it, i've created a debugging version. you can install it by running `pm install https://github.com/adielBm/Flow.Launcher.Plugin.Weather/blob/tmp-1.1.0-debug/Weather-1.1.0.zip` (you might need to uninstall the previous version first).

you can view the source code on the [tmp-1.1.0-debug branch](https://github.com/adielBm/Flow.Launcher.Plugin.Weather/tree/tmp-1.1.0-debug), where I've added `LogInfo` in some places for debugging.

thanks.

**Comment by adielbm** [comment]
Thank you for letting me know.

I couldn't find the reason for this error. It works fine for me.

You're saying that there are no logs, so if you'd like to help me fix it, I've created a debugging version. You can download it from: 
https://github.com/adielBm/Flow.Launcher.Plugin.Weather/blob/tmp-1.1.0-debug/Weather-1.1.0.zip
and then install it by `pm install FILE_PATH` (you might need to uninstall the previous version first).

You can see the source code on the [tmp-1.1.0-debug branch](https://github.com/adielBm/Flow.Launcher.Plugin.Weather/tree/tmp-1.1.0-debug), where I've added `LogInfo` in some places for debugging.

thanks

**Comment by enoversum** [comment]
> Thank you for letting me know.
> 
> I couldn't find the reason for this error. It works fine for me.
> 
> You're saying that there are no logs, so if you'd like to help me fix it, I've created a debugging version. You can download it from: https://github.com/adielBm/Flow.Launcher.Plugin.Weather/blob/tmp-1.1.0-debug/Weather-1.1.0.zip and then install it by `pm install FILE_PATH` (you might need to uninstall the previous version first).
> 
> You can see the source code on the [tmp-1.1.0-debug branch](https://github.com/adielBm/Flow.Launcher.Plugin.Weather/tree/tmp-1.1.0-debug), where I've added `LogInfo` in some places for debugging.
> 
> thanks

Hey there, there is no typical error popup in FlowLauncher, just the error in the window. FlowLauncher's own logs show no error message, and from the looks of it, it has something to do with connecting to Meteo. 
I'll install your debug version and will get back when I find anything :) .

**Comment by enoversum** [comment]
Edit: Unfortunately, I get an unspecified error when trying to install your plugin from Github. Double-checked that I didn't have any left-over folders from the previous installation, and even erased the settings for the plugin. So sorry this is becoming so difficult :( .

**Comment by adielbm** [comment]
you can uninstall by `pm uninstall Weather` 
and then install by 
`pm install https://github.com/adielBm/Flow.Launcher.Plugin.Weather/raw/tmp-1.1.0-debug/Weather-1.1.0.zip`

**Comment by enoversum** [comment]
> you can uninstall by `pm uninstall Weather` and then install by `pm install https://github.com/adielBm/Flow.Launcher.Plugin.Weather/raw/tmp-1.1.0-debug/Weather-1.1.0.zip`

I tried exactly that, but it didn't work. Now, after a complete restart of my computer, it would install, but says 'Weather data not found for Berlin', or any other location. 
With your build, I can now see a default city in settings, by the way.

Edit: Here is what the log says:

      17:06:56.8640+02:00 - INFO  - OpenMeteoApiClient.GetForecastAsync - Request URL: https://api.open-meteo.com/v1/forecast?latitude=52510885&longitude=133989367&current=temperature_2m,apparent_temperature,is_day,weather_code&daily=apparent_temperature_max,apparent_temperature_min&forecast_days=1
      17:06:57.1207+02:00 - INFO  - OpenMeteoApiClient.GetForecastAsync - Response Status Code: BadRequest
      17:06:57.1207+02:00 - INFO  - OpenMeteoApiClient.GetForecastAsync - Response Content: {"reason":"Latitude must be in range of -90 to 90°. Given: 5.2510884e+07.","error":true}
      17:06:57.1207+02:00 - WARN  - OpenMeteoApiClient.GetForecastAsync - No weather data found in response.
      17:07:08.5833+02:00 - ERROR - Infrastructure.Http.DownloadAsync - Http Request Error
      EXCEPTION OCCURS: System.Net.Http.HttpRequestException: Error code <BadRequest> returned from <https://i0.wp.com/seriallink.org/wp-content/uploads/2021/05/1200px-Adobe_Photoshop_CC_icon.svg_.png>
         at Flow.Launcher.Infrastructure.Http.Http.DownloadAsync(String url, String filePath, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Http\Http.cs:line 98
         at Flow.Launcher.Plugin.Notion.NotionDataParser.<>c__DisplayClass26_0.<<FileSave>b__0>d.MoveNext()

      17:07:09.1846+02:00 - INFO  - OpenMeteoApiClient.GetForecastAsync - Request URL: https://api.open-meteo.com/v1/forecast?latitude=52482157&longitude=133551901&current=temperature_2m,apparent_temperature,is_day,weather_code&daily=apparent_temperature_max,apparent_temperature_min&forecast_days=1
      17:07:09.2828+02:00 - INFO  - OpenMeteoApiClient.GetForecastAsync - Response Status Code: BadRequest
      17:07:09.2828+02:00 - INFO  - OpenMeteoApiClient.GetForecastAsync - Response Content: {"reason":"Latitude must be in range of -90 to 90°. Given: 5.2482156e+07.","error":true}
      17:07:09.2828+02:00 - WARN  - OpenMeteoApiClient.GetForecastAsync - No weather data found in response.
      17:07:40.9973+02:00 - INFO  - OpenMeteoApiClient.GetForecastAsync - Request URL: https://api.open-meteo.com/v1/forecast?latitude=52510885&longitude=133989367&current=temperature_2m,apparent_temperature,is_day,weather_code&daily=apparent_temperature_max,apparent_temperature_min&forecast_days=1
      17:07:41.0828+02:00 - INFO  - OpenMeteoApiClient.GetForecastAsync - Response Status Code: BadRequest
      17:07:41.0828+02:00 - INFO  - OpenMeteoApiClient.GetForecastAsync - Response Content: {"error":true,"reason":"Latitude must be in range of -90 to 90°. Given: 5.2510884e+07."}
      17:07:41.0828+02:00 - WARN  - OpenMeteoApiClient.GetForecastAsync - No weather data found in response.
      17:08:41.1152+02:00 - INFO  - OpenMeteoApiClient.GetForecastAsync - Request URL: https://api.open-meteo.com/v1/forecast?latitude=52510885&longitude=133989367&current=temperature_2m,apparent_temperature,is_day,weather_code&daily=apparent_temperature_max,apparent_temperature_min&forecast_days=1
      17:08:41.3208+02:00 - INFO  - OpenMeteoApiClient.GetForecastAsync - Response Status Code: BadRequest
      17:08:41.3208+02:00 - INFO  - OpenMeteoApiClient.GetForecastAsync - Response Content: {"error":true,"reason":"Latitude must be in range of -90 to 90°. Given: 5.2510884e+07."}
      17:08:41.3208+02:00 - WARN  - OpenMeteoApiClient.GetForecastAsync - No weather data found in response.

**Comment by enoversum** [comment]
(Of course, ignore the Notion plugin error message, and your log entries are from multiple tries to pull data for locations.)

**Comment by adielbm** [comment]
oh.. it's this: `latitude=52482157&longitude=133551901`.  however, on my pc it shows:

```
19:02:46.4523+03:00 - INFO  - OpenMeteoApiClient.GetForecastAsync - Request URL: https://api.open-meteo.com/v1/forecast?latitude=52.510885&longitude=13.3989367&current=temperature_2m,apparent_temperature,is_day,weather_code&daily=apparent_temperature_max,apparent_temperature_min&forecast_days=1
19:02:46.5243+03:00 - INFO  - OpenMeteoApiClient.GetForecastAsync - Response Status Code: OK
```

i'm working on it.

**Comment by adielbm** [comment]
i think it's related to some region setting:

![image](https://github.com/user-attachments/assets/820c73ec-7b75-4d3b-88f3-3fd6067c2b4f)

anyway, i tried to fix it

so i've made some changes here in this branch:
https://github.com/adielBm/Flow.Launcher.Plugin.Weather/tree/hotfix-double-parsing

and the zip here:
https://github.com/adielBm/Flow.Launcher.Plugin.Weather/blob/hotfix-double-parsing/Weather-1.1.0.zip

i'd like if you can verify it's working now. 

thanks a lot!

**Comment by enoversum** [comment]
Hey @adielBm , thank you so much for taking care of this. Unfortunately, I always get an error message when I try to install the version via 

> pm install https://github.com/adielBm/Flow.Launcher.Plugin.Weather/blob/hotfix-double-parsing/Weather-1.1.0.zip

I just won't install. I even tried to rule out some hanging on my machine by restarting it.

**Comment by adielbm** [comment]
thank you, too. sorry, it should've been:

```
pm install https://github.com/adielBm/Flow.Launcher.Plugin.Weather/raw/hotfix-double-parsing/Weather-1.1.0.zip
```

**Comment by enoversum** [comment]
> thank you, too. sorry, it should've been:
> 
> ```
> pm install https://github.com/adielBm/Flow.Launcher.Plugin.Weather/raw/hotfix-double-parsing/Weather-1.1.0.zip
> ```

Astonishing, it's working fine again. Getting all the information needed, also default city is working flawlessly here. Thank you so much, looking very good!

Are you planning on adding more weather providers in the future? I'm getting very good results with Foreca on an Android app I am using, not sure they have an all-access API though. Also, if you could add some forecast, that would be gold, but it's already very good at this state, so not complaining at all :) .

**Comment by adielbm** [comment]
I'm glad it's working well! I'll push this update in the next version soon, so you can install it regularly like `pm install weather`.

well i'm also working on adding more info something like:

![image](https://github.com/user-attachments/assets/1e64af29-9adc-4a5d-892e-a5715fc87fa5)

as for additional weather providers, I chose Open-Meteo because it doesn't require an API key. but, I'll look into adding others that might offer better results in the future.

**Comment by enoversum** [comment]
@adielBm Ah, well, that looks beautiful. You're really making an effort here into expanding your plugin's features. 

I don't think it's extremely necessary to add new providers, unless you want results to be super accurate. Most people will just be fine with the general weather with medium accuracy. And I don't know how accurate Open Meteo really is, as I have no experience with it. I just came from a long hunt for a weather app on Android, because many of them reported totally whacky results, and was happy to find out that one with Foreca as a provider works really reliably.
